spring:
  application:
    name: project-service
  datasource: 
    driver-class-name:  com.mysql.cj.jdbc.Driver
    name: defaultDataSource                           # 数据源名称
    url:  jdbc:mysql://175.178.33.209:3306/dailyreport?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC # 数据库连接地址
    username: dailyreport     #     数据库用户名&密码：
    password: W4hCLFbSwGJrHnYC
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8081
mybatis-plus:
  type-enums-package: com.bgp.project.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl